name: LocalNR
version: 1.0
date: 2017-07-18
description: |
    Package of local nearrings

authors:
    - name: Iryna Raievska
      url: http://www.imath.kiev.ua/~raeirina/
    - name: Maryna Raievska
      url: http://www.imath.kiev.ua/~raemarina/
    - name: Yaroslav Sysak
      url: http://www.imath.kiev.ua/~sysak/

maintainers:
    - name: Iryna Raievska
      url: http://www.imath.kiev.ua/~raeirina/
    - name: Maryna Raievska
      url: http://www.imath.kiev.ua/~raemarina/
    - name: Yaroslav Sysak
      url: http://www.imath.kiev.ua/~sysak/

GAP: ">=4.7.8"

needed-pkgs:
    - name: "SONATA"
      version: ">= 2.4"
      url: "https://gap-packages.github.io/sonata/"

www: https://gap-packages.github.io/LocalNR
readme: README.txt
packageinfo: https://gap-packages.github.io/LocalNR/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/LocalNR/releases/download/v1.0/LocalNR-1.0.tar.gz

abstract: |
    The <span class="pkgname">LocalNR</span> package contains the library of local nearrings up to order 361 and some functions to analyze finite nearrings.

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    local nearring, endomorphism, automorphisms group.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>RRS17</span>]   <b class='BibAuthor'>Raievska, I., Raievska, M. and Sysak, Y.</b>,
     <i class='BibTitle'>LocalNR, Package of local nearrings,
             Version 1.0</i>
     (<span class='BibYear'>2017</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/LocalNR">https://gap-packages.github.io/LocalNR</a></span>.
    </p>
    

bibtex: |
    @misc{ LocalNR1.0,
      author =           {Raievska, I. and Raievska, M. and Sysak, Y.},
      title =            {{LocalNR}, Package of local nearrings, {V}ersion 1.0},
      month =            {Jul},
      year =             {2017},
      note =             {GAP package},
      howpublished =     {\href                                        {https://gap-packages.github.io/LocalNR}
                          {\texttt{https://gap-packages.github.io/}\discretionary {}{}{}\texttt{LocalNR}}},
      keywords =         {local nearring; endomorphism; automorphisms group},
      printedkey =       {RRS17}
    }

